### PR TITLE
Merge CSS property definitions when possible

### LINKED ISSUE #662: Support multiple partial definitions of a CSS property
The /TR version of GCPM Level 3 contains two partial definitions for the `content` property:
- https://www.w3.org/TR/css-gcpm-3/#element-syntax
- https://www.w3.org/TR/css-gcpm-3/#leaders

Reffy does not know how to combine these definitions into and now throws an exception.

Via https://github.com/w3c/webref/pull/284#pullrequestreview-690294560

### LINKED ISSUE #663: Exclude CSS property definitions that describe "changes"
The /TR version of CSS 2.1 contains a Change section that describes [changes made to the definition of the `top` property](https://www.w3.org/TR/CSS21/changes.html#q21.523). Reffy picks up that change definition as a real definition and throws an exception because that property is already defined elsewhere.

There is no immediate markup that can be used to exclude the definition. Perhaps the most generic method would be to exclude definitions that have `<ins>` and `<del>` tags within the definition.

Via https://github.com/w3c/webref/pull/284#pullrequestreview-690294560

### PR DESCRIPTION
**Pull request by tidoust**
This makes the crawler merge CSS property definitions when it finds multiple definitions for a CSS property in the same spec. The merge operation remains basic: it merely merges the new values with the initial ones and hardly checks anything else. Fixes #662.

The update also makes Reffy ignore definitions that contain `<ins>` or `<del>` tags. Such definitions should only appear in "Changes" sections to detail changes that were made to the initial definition over time. Fixes #663.

### CODE REVIEW

File: src/browserlib/extract-cssdfn.mjs [hunk 1]
```diff
@@ -88,13 +88,58 @@ const extractDlDfn = dl => {
...
+  if (dfn1.name !== dfn2.name) {
+    return null;
+  }
+
+  // There should never be two base definitions for the same CSS property
+  if (dfn1.value && dfn2.value) {
+    return null;
+  }
+
+  const baseDfn = dfn2.value ? dfn2 : dfn1;
```
Comment (dontcallmedom) [inline src/browserlib/extract-cssdfn.mjs:110]: Maybe combine the assignments of base & partial to help with readability?
```suggestion
  const [baseDfn, partialDfn] = dfn2.value ? [dfn2, dfn1] : [dfn1, dfn2];
```

File: src/browserlib/extract-cssdfn.mjs [hunk 2]
```diff
@@ -88,13 +88,58 @@ const extractDlDfn = dl => {
...
+  if (!baseDfn.value && !baseDfn.newValues) {
+    return null;
+  }
+
+  const partialDfn = (baseDfn === dfn1) ? dfn2 : dfn1;
+  if (!partialDfn.newValues || partialDfn.initial) {
+    return null;
+  }
+  if (partialDfn.initial && partialDfn.initial !== baseDfn.initial) {
```
Comment (dontcallmedom) [inline src/browserlib/extract-cssdfn.mjs:119]: `partialDfn.initial` can't be true-ish at this stage given the previous condition, can it?

File: src/browserlib/extract-cssdfn.mjs [hunk 3]
```diff
@@ -103,7 +148,11 @@ const extractDfns = (doc, selector, extractor, { unique } = { unique: true }) =>
     .forEach(dfn => {
       if (res[dfn.name]) {
         if (unique) {
-          throw new Error(`More than one dfn found for CSS property/descriptor "${dfn.name}"`);
+          const merged = mergeDfns(res[dfn.name], dfn);
+          if (!merged) {
+            throw new Error(`More than one dfn found for CSS property "${dfn.name}" and dfns cannot be merged`);
```
Comment (dontcallmedom) [inline src/browserlib/extract-cssdfn.mjs:153]: just to be sure, we don't expect any current spec to throw, right?

File: src/browserlib/extract-cssdfn.mjs (hunk 2 above)
Comment (tidoust) [reply src/browserlib/extract-cssdfn.mjs]: Ooops. Previous condition shouldn't have been there. Removed.

File: src/browserlib/extract-cssdfn.mjs (hunk 3 above)
Comment (tidoust) [reply src/browserlib/extract-cssdfn.mjs:147]: The update is motivated by two current specs for which previous code throws. Once that is merged, all current specs should pass.

**Review by dontcallmedom — APPROVED** [review]
