### PR TITLE
Fix elements extraction for /TR version of SVG 1.1

### LINKED ISSUE #632: Elements extraction crashes on /TR version of SVG 1.1
See https://github.com/w3c/webref/blob/master/tr/index.json#L14461

### PR DESCRIPTION
**Pull request by tidoust**
Fixes #632

### CODE REVIEW

File: src/browserlib/extract-elements.mjs [hunk 1]
```diff
@@ -137,12 +137,12 @@ export default function () {
   // Extract SVG elements that use the "element-summary" pattern
   const svgSummaryElements = [...document.querySelectorAll('div.element-summary')]
     .map(el => {
-      const dfn = el.querySelector('.element-name dfn');
+      let dfn = el.querySelector('.element-name');
```
Comment (dontcallmedom) [inline src/browserlib/extract-elements.mjs:140]: why s/const/let/ ?
it's a bit confusing to keep the variable name `dfn` if this is no longer targeting the `dfn` element?

Comment (tidoust) [reply src/browserlib/extract-elements.mjs]: Ah, good point. I started the patch with an alternative, then realized I didn't need it and forgot to switch back to `const`.

**Review by dontcallmedom — APPROVED** [review]
